---
- name: Desplegar frontend (React + Nginx + proxy)
  hosts: frontend
  become: true

  vars:
    app_dir: /opt/gestor        # ajusta si usas otra ruta
    repo_url: https://github.com/pedritastark/gestor-tareas-ansible.git
    branch: master              # o main si tu rama principal se llama así

  tasks:
    # ─────────────────────── Dependencias básicas ──────────────────────────
    - name: Instalar curl y actualizar cache
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Agregar repo NodeSource 18.x
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Instalar Node.js y npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: no

    # ─────────────────────────────── Clon superficial ───────────────────────────────
    - name: Clonar repo (solo última versión)
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        depth: 1
        single_branch: yes

    # ─────────────────────────── Instalación y build ───────────────────────────────
    - name: Instalar dependencias frontend
      npm:
        path: "{{ app_dir }}/frontend"
        state: present

    - name: Compilar frontend (Vite → dist/)
      command: npm run build
      args:
        chdir: "{{ app_dir }}/frontend"

    # ─────────────────────────── Despliegue en Nginx ───────────────────────────────
    - name: Limpiar webroot actual
      file:
        path: /var/www/html
        state: absent

    - name: Copiar dist/ a /var/www/html
      copy:
        src: "{{ app_dir }}/frontend/dist/"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
