---
- name: Desplegar backend
  hosts: backend
  become: true
  vars:
    app_dir: /var/www/backend          # carpeta donde clonamos todo el repo
    repo_url: https://github.com/pedritastark/gestor-tareas-ansible.git
  tasks:
    # ──────────────────────────────────────────────────────────────────────────
    - name: Añadir repositorio NodeSource 18 LTS
      shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        warn: false

    - name: Instalar Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes
    # ──────────────────────────────────────────────────────────────────────────
    - name: Instalar PM2 de manera global
      npm:
        name: pm2
        global: yes
    # ──────────────────────────────────────────────────────────────────────────
    - name: Clonar el repositorio (sólo la rama principal, último commit)
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: master          # o main, según tu rama
        depth: 1
        single_branch: yes
    # ──────────────────────────────────────────────────────────────────────────
    - name: Instalar dependencias del backend
      npm:
        path: "{{ app_dir }}/backend"
        state: present
    # ──────────────────────────────────────────────────────────────────────────
    - name: Iniciar la API con PM2 (usa script "start")
      shell: pm2 start npm --name api -- start
      args:
        chdir: "{{ app_dir }}/backend"
    # ──────────────────────────────────────────────────────────────────────────
    - name: Configurar PM2 para autoiniciarse con el sistema
      shell: pm2 startup systemd -u ubuntu --hp /home/ubuntu && pm2 save
      args:
        creates: /etc/systemd/system/pm2-ubuntu.service
