---
- name: Deploy backend (Node + PM2)
  hosts: backend
  become: true

  vars:
    app_dir: /var/www/backend
    repo_url: "https://github.com/pedritastark/gestor-tareas-ansible.git"
    branch: "master"          # usa "main" si tu rama se llama main

  tasks:
    # --------------------------------------------------------------------
    - name: Ensure curl is present
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Add NodeSource 18.x repository
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes
    # --------------------------------------------------------------------
    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
    # --------------------------------------------------------------------
    - name: Clone repository (shallow)
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        depth: 1
        single_branch: yes
    # --------------------------------------------------------------------
    - name: Install backend dependencies
      npm:
        path: "{{ app_dir }}/backend"
        state: present
    # --------------------------------------------------------------------
    - name: Start API with PM2 (npm start)
      shell: |
        pm2 start npm --name api -- start
      args:
        chdir: "{{ app_dir }}/backend"

    - name: Enable PM2 on boot
      shell: |
        pm2 startup systemd -u ubuntu --hp /home/ubuntu
        pm2 save
      args:
        executable: /bin/bash
        creates: /etc/systemd/system/pm2-ubuntu.service
