---
- name: Desplegar backend
  hosts: backend
  become: true

  vars:
    app_dir: /var/www/backend                 # Directorio donde clonamos el repo
    repo_url: https://github.com/pedritastark/gestor-tareas-ansible.git

  tasks:

    # ────────────────────────────────── Node.js 18 ────────────────────────────
    - name: Añadir repositorio NodeSource 18 LTS
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        warn: false

    - name: Instalar Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    # ─────────────────────────────────── PM2 global ───────────────────────────
    - name: Instalar PM2 globalmente
      npm:
        name: pm2
        global: yes

    # ─────────────────────────────── Clonado del repositorio ──────────────────
    - name: Clonar el repositorio (rama principal, último commit)
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: master          # usa "main" si tu rama se llama main
        depth: 1
        single_branch: yes

    # ───────────────────────────── Dependencias del backend ───────────────────
    - name: Instalar dependencias del backend
      npm:
        path: "{{ app_dir }}/backend"
        state: present

    # ────────────────────────────── Arrancar API con PM2 ──────────────────────
    - name: Iniciar la API con PM2 (script "start")
      shell: pm2 start npm --name api -- start
      args:
        chdir: "{{ app_dir }}/backend"

    # ─────────────────────────────── PM2 autostart ────────────────────────────
    - name: Configurar PM2 para autoiniciarse tras reinicio
      shell: pm2 startup systemd -u ubuntu --hp /home/ubuntu && pm2 save
      args:
        creates: /etc/systemd/system/pm2-ubuntu.service
