---
- name: Desplegar backend (Node + PM2 + MongoDB)
  hosts: backend
  become: true

  vars:
    app_dir: /var/www/backend
    repo_url: "https://github.com/pedritastark/gestor-tareas-ansible.git"

  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes

    - name: Instalar curl
      apt:
        name: curl
        state: present

    - name: Añadir NodeSource 18.x
      shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args: { executable: /bin/bash }

    - name: Instalar Node.js
      apt:
        name: nodejs
        state: present

    - name: Instalar PM2 globalmente
      npm:
        name: pm2
        global: yes

    - name: Clonar repositorio (shallow)
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: master
        depth: 1
        single_branch: yes

    - name: Instalar dependencias del backend
      npm:
        path: "{{ app_dir }}/backend"
        state: present

    - name: Desplegar archivo .env
      template:
        src: env.j2
        dest: "{{ app_dir }}/backend/.env"
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Iniciar la API con PM2 (npm start)
      shell: pm2 start npm --name api -- start
      args:
        chdir: "{{ app_dir }}/backend"

    - name: Habilitar PM2 en el arranque
      shell: pm2 startup systemd -u ubuntu --hp /home/ubuntu && pm2 save
      args:
        creates: /etc/systemd/system/pm2-ubuntu.service
