---
- name: Desplegar frontend (React + Nginx + proxy)
  hosts: frontend
  become: true

  vars:
    app_dir: /opt/gestor
    repo_url: "https://github.com/pedritastark/gestor-tareas-ansible.git"
    branch: master

  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes

    - name: Instalar curl y xz-utils
      apt:
        name:
          - curl
          - xz-utils
        state: present

    - name: Añadir NodeSource 18.x
      shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args: { executable: /bin/bash }

    - name: Actualizar caché tras NodeSource
      apt:
        update_cache: yes

    - name: Instalar Node.js (incluye npm)
      apt:
        name: nodejs
        state: present

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Clonar repositorio (shallow)
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        depth: 1
        single_branch: yes

    - name: Instalar dependencias frontend
      npm:
        path: "{{ app_dir }}/frontend"
        state: present

    - name: Compilar frontend (Vite → dist/)
      command: npm run build
      args:
        chdir: "{{ app_dir }}/frontend"

    - name: Limpiar webroot
      file:
        path: /var/www/html
        state: absent

    - name: Crear directorio webroot
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copiar dist/ al webroot (remote)
      copy:
        src: "{{ app_dir }}/frontend/dist/"
        dest: /var/www/html/
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Desplegar configuración de Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
