---
- name: Desplegar frontend (React + Nginx + proxy)
  hosts: frontend
  become: true

  vars:
    app_dir: /opt/gestor
    repo_url: https://github.com/pedritastark/gestor-tareas-ansible.git
    branch: master

  tasks:
    # ─────────────────────────────── Actualizar cache ──────────────────────────────
    - name: Actualizar caché de apt
      apt:
        update_cache: yes

    # ────────────────────────── Agregar NodeSource y actualizar ───────────────────────
    - name: Añadir repo NodeSource 18.x
      shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Actualizar caché tras NodeSource
      apt:
        update_cache: yes

    # ──────────────────────────────── Instalar Node.js ────────────────────────────────
    - name: Instalar Node.js (incluye npm)
      apt:
        name: nodejs
        state: present

    # ───────────────────────────── Instalación de Nginx ─────────────────────────────
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    # ───────────────────────────── Clonar repo (shallow) ─────────────────────────────
    - name: Clonar repo (último commit)
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        depth: 1
        single_branch: yes

    # ────────────────────────── Instalar deps y build Vite ───────────────────────────
    - name: Instalar dependencias frontend
      npm:
        path: "{{ app_dir }}/frontend"
        state: present

    - name: Compilar frontend (Vite → dist/)
      command: npm run build
      args:
        chdir: "{{ app_dir }}/frontend"

    # ─────────────────────────── Desplegar en Nginx ────────────────────────────────
    - name: Limpiar webroot
      file:
        path: /var/www/html
        state: absent

    - name: Copiar dist a /var/www/html
      copy:
        src: "{{ app_dir }}/frontend/dist/"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
